<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Captcha.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="SixLabors.Fonts" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\SRH.Libraries\SRH.PrimitiveTypes\SRH.PrimitiveTypes.csproj" />
	</ItemGroup>

</Project>
