<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SpaRoot>..\..\..\bazneshastegi.client</SpaRoot>
		<SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
		<SpaProxyServerUrl>https://localhost:51035</SpaProxyServerUrl>
	</PropertyGroup>

	<PropertyGroup>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Resources\**" />
		<EmbeddedResource Remove="Resources\**" />
		<Content Remove="Resources\**" />
		<None Remove="Resources\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\bazneshastegi.client\bazneshastegi.client.esproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\..\SRH.Libraries\SRH.ServiceInstaller\SRH.ServiceInstaller.csproj" />
		<ProjectReference Include="..\Bazneshastegi.Contracts\Bazneshastegi.Contracts.csproj" />
		<ProjectReference Include="..\Bazneshastegi.Infrastructure\Bazneshastegi.Infrastructure.csproj" />
		<ProjectReference Include="..\Bazneshastegi.Presentation\Bazneshastegi.Presentation.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SpaProxy"></PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
	</ItemGroup>

</Project>
