namespace Bazneshastegi.Contracts.UserContracts.SigninContracts.SigninWithMobileContracts.SendOtpToExistingMobileContracts;

public readonly record struct SendOtpToExistingMobileApiResponse(string Otp);
